- autoload/elm.vim
commit 1 fixes an off-by-one that caused incorrect completions and/or crashes
commit 2 makes the crashes behave a bit better (they can still happen if e.g. you're not in an elm package when editing, which I'd also like to fix later)
> Completion fixes

- ftplugin/elm.vim
`commentstring` is needed to work with @tpope's vim-commentary
(https://github.com/tpope/vim-commentary)
Thank you for making this – it's neat!
> Add commentstring and comments settings

- autoload/elm.vim
(more detail in the commit message)
This makes autocomplete work regardless of the user's working directory, by finding the package's root dir by looking for `elm-stuff` in parent directories of the file.
If it can't find it it raises an error. I'd prefer that to be less disruptive but don't know a great way of showing warnings in vim while in insert mode. It's at least a nicer error now. :)
> find elm-stuff relative to file; err if not found

- autoload/elm.vim
List of allowed symbols based on:
https://github.com/Apanatshka/elm-spoofax/blob/master/syntax.ebnf
I've also escaped values used in `system` calls to avoid any issues with special characters.
Fixes #17
> Fix elm-oracle integration to accept identifiers with symbols

- syntax/elm.vim
Although other languages have special language keywords for `true` and `false`, Elm implements `True` and `False` as plain old union types. Highlighting them differently than (for example) `Nothing` or `Result` or `Task` subtly suggests they play by different rules than other union types, when they actually do not.
This PR makes the formatting consistent across union types by removing the special case for `True` and `False`, and also removes special highlighting for `otherwise`, as `otherwise` was removed from Core in 3.0.0. :smiley:
> Highlight True and False as normal union types

- ftplugin/elm.vim
Pressing `gf` on a module name (or import) will go to that file.
```
module Foo where
import Bar
import Json.Decode
```
So pressing `gf` on `Bar` would go to `src/Bar.elm`, while doing it on `Json.Decode` would go to `elm-stuff/.../src/Json/Decode.elm`
This assumes that source code is in `src` and that dependencies are installed
in `elm-stuff`. Ideally we should improve using all paths referenced in `package.json`, but it's a good baseline.
> Enables go to file for module names/imports

- autoload/elm.vim
It's annoying that all folds get closed on write with elm-format enabled.
Steal a solution from [vim-go](https://github.com/fatih/vim-go/pull/691) ;)
> elm-format: save folds on buffer write

- doc/elm-vim.txt
Hey,
I've reformatted lines in the documentation which exceed the 80 char textwidth to improve readability.
Hope that's ok!
> Reformat documentation paragraphs to match textwidth

- ftplugin/elm.vim
This allows path-searching functions like `[I` to know which files are
included, so it knows which files to search
> Set up include option

- syntax/elm.vim
Since strings are usually intended for display, I want spelling errors to show up in my strings when I have spell an syntax highlighting on.  Added to both single and triple quoted strings.
> show spelling errors in strings

- syntax/elm.vim
The elm compiler accepts integer literals in hex, so they should be highlighted.
> Highlight hexadecimal integer literals

- autoload/elm.vim
- autoload/elm/util.vim
- ftplugin/elm.vim
`elm#Format()` is triggered pre write of a buffer. This causes echoed
messages to be cleared before the user actually sees them. By storing
messages for later use, using `elm#util#EchoLater` we can overcome this
problem.
This pull request addresses issue #57
Extra thanks to @Raimondi for helping me figuring this one out!
> Allow messages to be echoed later

- autoload/elm.vim
When using loclist, sometimes it contains incorrect entries, as error location
came from other file. This happens because errors produced by `elm-make` often
span across many files, not only current one (because of imports), so it makes
sense to use quickfix list to navigate errors.
> Use quickfix list instead of location list

- autoload/elm/util.vim
This fixed #80 for me on:
OS X 10.11.6
VIM 7.3
From `:help :call`:
> You can call and define functions by an evaluated name [...]
Example:
:let func_end='whizz'
:call my_func_{func_end}(parameter)
> Fixes #80 Trailing characters error with elm-format on save

- ftplugin/elm.vim
I noticed that the longer vim ran, the slower the elm-format upon save functionality seemed to become. It turns out the cause of this is that for every .elm file that is opened, a new set of BufWrite hooks is registered. This means that after navigating around the project a bit, saving a file is going to invoke elm-format multiple times in succession, which is slow and pointless.
This PR fixes that by always clearing the relevant commit hooks before registering them again.
> Ensure vim hooks are registered only once

- autoload/elm.vim
Current implementation of `elm#Syntastic` does not populate `s:errors`, causing `ElmErrorDetail` to show nothing/outdated details. 
Fixes #106.
> Add support for ElmErrorDetail when using syntastic

- indent/elm.vim
There are some small indentation bugs that don't conform to the elm style guide and in some cases can actually lead to code that doesn't compile.
According to the [style guide](http://elm-lang.org/docs/style-guide), multi-line union types should have the following indentation:
```
type Boolean
= Literal Bool
| Not Boolean
| And Boolean Boolean
| Or Boolean Boolean
```
Due to an omitted `=` operator in a regex, elm-vim was indenting this as:
```
type Boolean
= Literal Bool
| Not Boolean
| And Boolean Boolean
| Or Boolean Boolean
```
This has been fixed by amending the regex.
There was also a missing word boundary near one of the indentation checks for the `in` keyword. This was causing function names with `in` as a prefix to indent if there is a type annotation on the line above it (this …
> Indentation Fixes

- autoload/elm.vim
- autoload/elm/util.vim
- ftplugin/elm.vim
I depend on `gf` a lot to navigate around a project, but noticed it doesn't behave as expected under certain circumstances. This PR makes `gf` behave correctly under almost all circumstances, at least that is my experience trying it out on a large Elm project.
In particular it fixes these issues:
- Works regardless of current working directory.
- Finds module shadowed by a directory with the same name.
- Finds modules outside of the /src directory.
- Finds native modules.
Implementation requires a custom binding of `gf` in .elm files. This is an approach also taken by plugins like `vim-rails` and `vim-node`.
> Improve gf command

- ftplugin/elm.vim
The `gf` mapping should be buffer local, otherwise it clobbers the normal built-in behaviour of `gf` while editing other non-elm files in the same vim session.
> make custom gf mapping buffer local

- ftplugin/elm.vim
:command occurs errors when it command is reloaded :cry:
:command! define it again (and the errors is not happend)
> Use :command! instead of :command

- autoload/elm.vim
- ftplugin/elm.vim
I added a command to install required npm packages. It is inspired by vim-go's `GoInstallBinaries` command.  
This is the simplest implementation of `ElmInstallExecutables`, just calling system commands.
I recommend to merge #142 before merging this PR because I use `command!` instead of `command` in the code.
> Add ElmInstallExecutables command

- syntax/elm.vim
This just updates the syntax highlighting for multiline type declarations from
To
> Multiline type declaration highlighting

- ftplugin/elm.vim
Fixes #123. Possible better solution than #144.
Thank you @tpope and others for explaining the issue and fix.
Tested on macOS 10.13.4 with Vim (8.0.1750) and Neovim (0.2.2).
> Cleanup commands on plugin unload

- autoload/elm.vim
Was running into an issue with `:ElmTest` in elm 0.19.0 where it was unable to find the root directory. Did a little digging, and found that `elm#FindRootDirectory` only looks for `elm-package.json`, and not `elm.json`.
So I added a fallback so that if an `elm-package.json` cannot be found, `FindRootDirectory` will look for an `elm.json` file before returning an empty string. After `Plug`ing my forked repo, this fix appears to have the desired behavior.
I'm a total vimscript noob, though, so please let me know if anything looks off.
> Add elm.json fallback to FindRootDirectory

- README.md
Correct the readme -> keybindings to use `LocalLeader`, which is consistent with the implementation as seen here: https://github.com/ElmCast/elm-vim/blob/d22c0ba13afb554257a8c176962e2216cc18edd1/ftplugin/elm.vim#L66-L72.
> Correct the leader type in keybinding

- syntax/elm.vim
I noticed in other ML language syntax highlighters that the function name is highlighted (for instance see [Sublime's syntax](https://packagecontrol.io/packages/Elm%20Language%20Support)) which makes it useful to distinguish a function from its parameters.
The function name is only highlighted if it is not nested (i.e., at the beginning of the line) otherwise variables would be highlighted as functions.
> Update syntax to highlight function name

- autoload/elm/util.vim
Elm .19 uses elm.json instead of elm-package.json, so we should support both when trying to find local modules.
> Find local modules in Elm .19 as well as older versions.
